[tool.poetry]
name = "2d-arm"
version = "0.1.0"
description = "2D Robot Arm"
authors = ["Zach <reklaw0x@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
